version: '3.9'
services:
  db:
    image: mysql:8.0.33
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: Estudo123
      MYSQL_USER: estudo
      MYSQL_PASSWORD: Estudo123
      MYSQL_DATABASE: backendestopenda
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - "3308:3308"
    expose:
      - 3308
    networks:
      - estopenda-network
  backendestopenda:
    image: arthurcabral/backendestopenda
    restart: always
    build: ./Project
    working_dir: /Project
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/backendestopenda
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: Estudo123
    ports:
      - "80:80"
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - estopenda-network
networks:
  estopenda-network:
    driver: bridge
