cors:
  originPatterns: http://localhost:80,http://localhost:3000
security:
  jwt:
    token:
      secret-key: ${API_KEY}
      expíre-length: 3600000
server:
  port: 80
spring:
  config:
    import: file:env.yml
  datasource:
    url: jdbc:mysql://localhost:3306/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      show-sql: false
spring-doc:
  swagger-ui:
    use-root-path: true