name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ SECRETS.DOCKER_USERNAME }}
        password: ${{ SECRETS.DOCKER_PASSWORD }}
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      working-directory: ./BackEstopendaGit/BackEstopenda
      run: mvn clean package -DskipTests

    - name: Docker Compose Build
      working-directory: ./BackEstopendaGit
      run: docker compose build

    - name: Push Docker Image to Docker Hub
      run: |
        docker tag ${{ SECRETS.DOCKER_USERNAME }}/backendestopenda:latest docker tag ${{ SECRETS.DOCKER_USERNAME }}/backendestopenda:${{ github.run_id }}
        docker push ${{ SECRETS.DOCKER_USERNAME }}/backendestopenda:${{ github.run_id }}
        docker push ${{ SECRETS.DOCKER_USERNAME }}/backendestopenda:latest
